services:
  # 1. Container untuk Aplikasi Laravel Kamu (Port Luar: 8002)
  app-order:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"         # <--- Diubah agar luar ketuk 8002, masuk ke dalam port 8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db-order
      - redis-broker

  # 2. Container untuk Database MySQL (Port Luar: 3309)
  db-order:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_order_payment
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3309:3306"         # <--- Diubah ke 3309 agar tidak bentrok dengan MySQL bawaan laptop / Rafli
    volumes:
      - db_data_order:/var/lib/mysql

  # 3. Container untuk Message Broker (Redis)
  redis-broker:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db_data_order: